### ISSUE TITLE
Use OpenKit through proxy

### ISSUE THREAD

**Issue by naulacambra** [Dynatrace/openkit-dotnet#115]
I'm trying to use this package to send data to our DynaTrace dashboard, but it seems that it cannot go through our proxy (behind which is our server).

```
System.AggregateException: One or more errors occurred. (No connection could be made because the target machine actively refused it) ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at Dynatrace.OpenKit.Protocol.HTTPClient.SendRequestInternal(RequestType requestType, String url, String clientIPAddress, Byte[] data, String method)
   at Dynatrace.OpenKit.Protocol.HTTPClient.SendRequest(RequestType requestType, String url, String clientIPAddress, Byte[] data, String method)
---> (Inner Exception #0) System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)<--- 
```

There is any way to set the proxy info?

**Comment by stefaneberl** [comment]
Hi,
thanks for the question. According to some sources, it should work for .NET apps if you either configure IE with proxy settings or add it to your app.config/web.config, as described here https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings.

Please let me know which .NET framework you are using and which version, as there are different implementations of the HTTP communication.

Best regards
Stefan

**Comment by naulacambra** [comment]
Hi @stefaneberl

> Please let me know which .NET framework you are using and which version, as there are different implementations of the HTTP communication.

I'm using .NET Core 2.2


> According to some sources, it should work for .NET apps if you either configure IE with proxy settings...

The proxy is already configured in the server


> ...or add it to your app.config/web.config, as described here https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings.

This documentation seems to work for .NET Framework but not for .NET Core.

**Comment by stefaneberl** [comment]
Hi @naulacambra,

based on quick research it is possible, as the HttpClientHandler (https://github.com/dotnet/corefx/blob/release/2.2/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Windows.cs) does support this out of the box. By default `WindowsProxyUsePolicy.UseWinInetProxy` enum value is used. This should then respect the settings from the system (Internet Explorer), WPAD or PAC.

Nevertheless, I do agree that the way how to manually configure a proxy is not ideal in OpenKit (.NET/Java/C++). This will be refactored in a future version to provide more flexibility in HTTP communication.

For now, the easiest workaround is to fork this repository, check out the `release/1.4` branch and modify the class `HTTPClientHttpClient`.
Replace the method `CreateHTTPClient` (line 134) with the following
```cs
private System.Net.Http.HttpClient CreateHTTPClient()
{
    var proxy = new WebProxy(...); // use the appropriate CTOR here
    var httpClientHandler = new System.Net.Http.HttpClientHandler
    {
        ServerCertificateCustomValidationCallback = configuration.SSLTrustManager.ServerCertificateValidationCallback.Invoke,
        Proxy = proxy
    };
    return new System.Net.Http.HttpClient(httpClientHandler, true);
}
```

**Comment by stefaneberl** [comment]
Hi @naulacambra,

did the suggestion work for you?

Best regards
Stefan

**Comment by stefaneberl** [comment]
Closing, as there is no further feedback.
